AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  AuroraUsername:
    Type: String
    Description: Master user name for the Aurora Cluster
  AuroraPassword:
    Type: String
    Description: Master password for the Aurora Cluster


Resources:

  GetAuroraItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.serverless.lambda.GetAuroraItemFunction::handleRequest
      Timeout: 15
      MemorySize: 128
      CodeUri: .
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
           - Effect: Allow
             Action:
              - rds-data:*
             Resource: '*'
           - Effect: Allow
             Action:
               - secretsmanager:GetSecretValue
             Resource: !Ref AuroraSecret
      Environment:
        Variables:
          AuroraClusterArn: !Sub 'arn:aws:rds:${AWS::Region}:${AWS::AccountId}:cluster:${AuroraServerlessCluster}'
          DatabaseName: booksdb
          AuroraSecretArn: !Ref AuroraSecret
      AutoPublishAlias: dev

  AuroraServerlessCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: serverless
      DatabaseName: booksdb
      MasterUsername: !Ref AuroraUsername
      MasterUserPassword: !Ref AuroraPassword
      EnableHttpEndpoint: true

  AuroraSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      SecretString: !Sub '{"username":"${AuroraUsername}","password":"${AuroraPassword}", "dbClusterIdentifier":"${AuroraServerlessCluster}"}'