AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  GetAuroraItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      Handler: com.home.amazon.serverless.lambda.GetAuroraItemFunction::handleRequest
      Timeout: 60
      MemorySize: 512
      CodeUri: .
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
           - Effect: Allow
             Action:
              - rds:*
             Resource: '*'
      Environment:
        Variables:
          DatabaseName: books

  AuroraServerlessCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: serverless
      DatabaseName: books
      MasterUsername: rostyslavadmin
      MasterUserPassword: rostyslavadmin
      EnableHttpEndpoint: true